### ISSUE TITLE
basic example and tests doesn't work

### ISSUE THREAD

**Issue by moskiteau** [intel/daal-extensions#1]
with the latest daal 2018 update 2 and pydall 2018
`
======================================================================
ERROR: test_mlp (tests.nn_test.TestDAALNet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/seb/daal/daal-extensions/pydaal-contrib/pydaalcontrib/tests/nn_test.py", line 128, in test_mlp
    net = DAALNet().build(model)
  File "/home/seb/daal/daal-extensions/pydaal-contrib/pydaalcontrib/nn/net.py", line 49, in __init__
    self.net = training.Batch()
  File "/home/seb/miniconda2/lib/python2.7/site-packages/daal/algorithms/neural_networks/training.py", line 1032, in __new__
    return Batch_Float32FeedforwardDense(*args)
  File "/home/seb/miniconda2/lib/python2.7/site-packages/daal/algorithms/neural_networks/training.py", line 723, in __init__
    this = _training19.new_Batch_Float32FeedforwardDense(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'new_Batch_Float32FeedforwardDense'.
  Possible C/C++ prototypes are:
    daal::algorithms::neural_networks::training::interface1::Batch< float,daal::algorithms::neural_networks::training::feedforwardDense >::Batch(daal::services::SharedPtr< daal::algorithms::optimization_solver::iterative_solver::Batch >)
    daal::algorithms::neural_networks::training::interface1::Batch< float,daal::algorithms::neural_networks::training::feedforwardDense >::Batch(daal::algorithms::neural_networks::training::interface1::Batch< float,daal::algorithms::neural_networks::training::feedforwardDense > const &)

`

**Comment by jumutc** [comment]
Hi @moskiteau,

It seems like you are using an old version of *pydaalcontrib*. I can see that at line 49 in `daal-extensions/pydaal-contrib/pydaalcontrib/nn/net.py` I have `self.net = training.Batch(self.solver)` instead of `self.net = training.Batch()` which is the correct usage for `pydaal`. Could you confirm?

**Comment by moskiteau** [comment]
I confirm, it does work now, thanks
